"addi t2, zero, 16;"//arr size
"addi t1, zero, 0;"// counter
"addi %[arith_cnt], zero, 2;"
"addi %[lw_cnt], zero, 0;"
"addi %[sw_cnt], zero, 0;"
"addi %[others_cnt], zero, 0;"
"loop: "
"addi t1, t1, 1;"
"addi %[arith_cnt], %[arith_cnt], 1;"
"lw t3,0(%[h]);"
"lw t4,0(%[x]);"
"addi %[lw_cnt], %[lw_cnt], 2;"
"add t3, t3, t4;"
"addi %[arith_cnt], %[arith_cnt], 1;"
"sw t3 ,0(%[y]);"
"addi %[sw_cnt], %[sw_cnt], 1;"
"addi %[h], %[h], 2;"
"addi %[x], %[x], 2;"
"addi %[y], %[y], 2;"
"addi %[arith_cnt], %[arith_cnt], 3;"
"addi %[others_cnt], %[others_cnt], 1;"
"bne t1,t2,loop;"
